name: Deploy to GitHub Pages
on:
  push:
    branches: [main] # ou master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x # ou a versão que você utiliza
      - name: Publish
        run: dotnet publish HelloBlazor/HelloBlazor.csproj -c Release -o release --nologo
      - name: Commit Files
        run: |
          cd release/wwwroot
          git init
          git add .
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -m "Deploy to GitHub Pages"
          git push --force "https://github.com/${{ github.repository }}.git" master:gh-pages
