name: Deploy to GitHub Pages
on:
  push:
    branches: [main] # ou master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. Instala o .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x" # Use a versão do seu projeto

      # 2. Faz o Publish (Build) do Blazor
      - name: Publish Project
        run: dotnet publish -c Release -o release

      # 3. Prepara os arquivos específicos para o GitHub Pages
      - name: Prepare for GH Pages
        run: |
          cd release/wwwroot
          touch .nojekyll
          cp index.html 404.html

      # 4. Faz o Push automático para a branch gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./release/wwwroot
